plugins {
    id "com.android.application"
}

android {
    namespace "com.k16.camera"
    compileSdk 35

    defaultConfig {
        applicationId "com.k16.camera"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "2.0.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
